spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wcc
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  jwt-signing-key: 5hVgfl9qOUMvkLJnrQhZvRf1dblyxRDRtlwIcPow+Bs=

